visdom_config:
  visualize: true
  plot_frequency: 1
  config_file: "config/rl/docker_visdom.json"
  env_name: "egreedy_qtiled_sprime"
  rewrite_windows: true

execute_post_episode: 100
num_episodes: 8000
change_seeds: true
rate: -1
save_path: "data/task1/models"
save_prefix: "egreedy_qtiled_sprime"
save_suffix: ''
save_every: 100

task:
  state_vector_args:
    history_buffer: 0
  rewards:
    drawer: 3000.0
    box: 300.0
    batteries: 1000.0
    flashlight: 1000.0
    apple: 50.0
    time_penalty: -0.01
    fail_penalty: -200.0
    timeout_penalty: -100.0
  timeout: 5000

agent:
  epsilon_start: 0.14
  epsilon_decay_factor: 0.99
  epsilon_bias: 0.01
  alpha_start: 0.1
  alpha_decay_factor: 1000
  alpha_bias: 0.0
  gamma: 0.9
  num_tiles: 512
  tiles_max_size: 1048576
  missing_param_value: -5
  use_iht: false
