visdom_config:
  visualize: true
  plot_frequency: 1
  config_file: "config/rl/docker_visdom.json"
  env_name: "main"
  rewrite_windows: true

execute_post_episode: 500
num_episodes: 10000
change_seed: true
rate: -1
save_path: "data/task1/models"
save_prefix: "template"
save_suffix: ''

task:
  state_vector_args:
    state_positions: false
    state_semantics: true
    position_semantics: true
    history_buffer: 0
  subgoal_reward: 500.0
  time_penalty: -0.5
  fail_penalty: -110.0
  timeout_penalty: -100.0
  timeout: 100

agent:
  epsilon_start: 0.15
  epsilon_decay_factor: 0.9995
  alpha_start: 0.1
  alpha_decay_factor: 1000
  gamma: 0.9
  default_Q: 0.0
